---
title: "Trade data sources"
date: "`r Sys.Date()`"
output: html_document
---

# COMTRADE

## Regular download

## Bulk download

# World Bank

## WITS Trade data

### Customizing county aggregates

### Customizing commodity aggregates

## WITS Tarriffs data

## TCdata360

http://tcdata360.worldbank.org/

# Observatory of Economic Complexity (powerful data exploration tool)

http://atlas.media.mit.edu/en/ 

# ITC Trade Map

http://www.trademap.org/

# WTO data

## Trade time series

http://stat.wto.org/Home/WSDBHome.aspx?Language=

## WTO Tarrifs database

http://tariffdata.wto.org/ that’s the website I also used for tariff data.

This is an extract of what Katia sent me, regarding a request for leave at the end of September I made: 

“you should work very intensively with Eduard until that time in order to complete the transfer of know-how regarding data extraction and analysis. Please ensure that he can dedicate time to this until your leave”

I could also try to postpone my leave by one week, when is it that you leave FAO?

Also, regarding the new computer:

“Regarding the computer, we can certainly ask to purchase one, but keep in mind that these orders take a long time. Can you not keep the machine that Eduard uses now after he leaves?”

I imagine this is not really an option as I need a new computer to learn, no? Or how is it exactly?


```{r knitr_init, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

