---
title: "Other trade data sources"
author: "Eduard Bukin"
date: '2017-09-03'
---

---


## [Global Trade Atlas (GTA)](https://www.ihs.com/products/maritime-global-trade-atlas.html)

This is a trade data sources (formerly) purchased by FAO and available to the users with the ligin creditentials. To find more information about it, please contact to Adam Prakash. 

## [UNCTAS STAT](http://unctadstat.unctad.org/EN/)

Statistical tools maintained and supported by UNCTAD. It gives access to basic and derived indicators built upon common rules, harmonized environment and clear methodology supported by powerful data browsing system.

## [EU Customs data](http://ec.europa.eu/ecip/information_resources/databases/index_en.htm)

The Commission develops and operates several databases in conjunction with Member States' Customs and Taxation Services. The databases are part of the information systems of Taxation and Customs Union. Although VIES has been developed and is operated at a national level, it can also be accessed via this site.

## [EU The Market Access Database](http://madb.europa.eu/madb/indexPubli.htm)

The Market Access Database (MADB) gives information to companies exporting from the EU about import conditions in third country markets:
