---
title: "Overview of trade data sources"
author: "Eduard Bukin"
date: "September 22, 2017"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Trade data sources: Overview

Today, we will go through the main sources of trade data, which could be used in the trade data analysis. 

All information presented today is on the website:

**[https://ebukin.github.io/dataManipulationPractice/](https://ebukin.github.io/dataManipulationPractice/)**

Content: 

*  General information
*  UN Comtrade
*  World Bank
*  World Trade Organization
*  International Trade Center
*  MIT-Harvard `Economic Complexity` Solutions
*  CEPII
*  Shiny trade analysis tool
*  R package for trade data analysis

## General information

### Trade classifications (What are those? Why those are different? Where to find them?)

-  [Harmonized System - HS](http://www.wcoomd.org/en/topics/nomenclature/instrument-and-tools/hs-nomenclature-2017-edition.aspx)
-  [Standard International Trade Classification - SITC](https://unstats.un.org/unsd/cr/registry/regcst.asp?Cl=28&Lg=1)
-  [Broad Economic Categories - BEC](https://unstats.un.org/unsd/cr/registry/regcst.asp?Cl=10&Lg=1)

### Other products classifications
    
-  [FAO Commodity list - FCL](http://www.fao.org/economic/ess/ess-standards/commodity/en/)
-  [Central Product Classification - CPC](https://unstats.un.org/unsd/cr/registry/regcst.asp?Cl=14)
-  [List of all UNSD classifications](https://unstats.un.org/unsd/cr/registry/regct.asp?Lg=1)
-  [UN Methodology for mapping classifications](https://unstats.un.org/unsd/trade/classifications/corr-notes/HS2017%20conversion%20to%20earlier%20HS%20versions%20and%20other%20classifications.pdf)
    
### Areas Classification
    
-  [m49 - UNSD classification](https://unstats.un.org/unsd/methodology/m49/)
-  [FAOSTAT - Country List](http://www.fao.org/faostat/)
-  [Other FAO classifications](http://www.fao.org/countryprofiles/iso3list/en/)
    
### Asymmetry of information

-  CIF vs FOB values
-  Data Availability and data sources.
    
## One exercise/example

Select data for:

*  Ukraine
*  Annual 
*  Commodities
*  HS Code 1001 - Wheat
*  2010-2015
*  Trade with the world and some 

Analyze trade by regions:

*  Use All Agrifood trade according to WTO classification
*  Analyse this trade by Country groups (LDC and LIC)

    
## UN Comtrade data
    
### Data availability
    
*  Trade availability visualization tool [https://comtrade.un.org/data/da](https://comtrade.un.org/data/da)
*  [API interface](https://comtrade.un.org/data/Doc/API#DataAvailabilityRequests)
    
### Regular download [https://comtrade.un.org/data/](https://comtrade.un.org/data/)

### Bulk download 
    
*  Web based [https://comtrade.un.org/data/bulk](https://comtrade.un.org/data/bulk)
*  API [https://comtrade.un.org/data/doc/api/bulk/](https://comtrade.un.org/data/doc/api/bulk/)
    
### Restricted access and [Token authentication](https://comtrade.un.org/data/auth/login?ReturnUrl=%2Fdata%2Fbulk)
    
### Data visualization options [https://comtrade.un.org/labs/](https://comtrade.un.org/labs/)

### Metadata [https://unstats.un.org/unsd/tradekb/Knowledgebase/13](https://unstats.un.org/unsd/tradekb/Knowledgebase/13)

### Country publication notes [https://comtrade.un.org/db/mr/daPubNoteDetail.aspx](https://comtrade.un.org/db/mr/daPubNoteDetail.aspx)

## World Bank

### WITS [http://wits.worldbank.org/](http://wits.worldbank.org/)
    
*  Registration / Log in 
*  Advance query - Trade Data
*  Advance query - Trade Data
*  User defined groups of commodities and countries
*  Tariffs data
*  Trade indicators
    
### TCdata360 [https://tcdata360.worldbank.org/](https://tcdata360.worldbank.org/)

## World Trade Organization data

-  Tariff Analysis Online tool [http://tao.wto.org/](http://tao.wto.org/);
-  Tariff Download Facility [http://tariffdata.wto.org/](http://tariffdata.wto.org/).
-  Regional Trade Agreement Information System (RTA-IS) [http://rtais.wto.org/](http://rtais.wto.org/);
-  Trade data time series [http://stat.wto.org/](http://stat.wto.org/);

##  International Trade Center data [- some overview]https://ebukin.github.io/dataManipulationPractice/00-itc-trademap.html

*  Trade Map [http://www.trademap.org/Index.aspx](http://www.trademap.org/Index.aspx)
*  Market Access Map [http://www.macmap.org/Main.aspx](http://www.macmap.org/Main.aspx)
*  Standards Map [http://www.standardsmap.org](http://www.standardsmap.org)
*  Investment Map [http://www.investmentmap.org](http://www.investmentmap.org)
*  Trade competitiveness Map [http://tradecompetitivenessmap.intracen.org/](http://tradecompetitivenessmap.intracen.org/) 

##  CEPII

-  Databases: [http://www.cepii.fr/](http://www.cepii.fr/).
    *  [BACI](http://www.cepii.fr/CEPII/en/bdd_modele/presentation.asp?id=1)
    *  Other data bases.

##  MIT-Harvard `Economic Complexity` Solutions

*  [The Observatory of Economic Complexity](http://atlas.media.mit.edu/en/)

*  [Atlas of economic complexity](http://atlas.cid.harvard.edu)

*  [Globe of economic complexity](http://globe.cid.harvard.edu/)

##  Shiny trade analysis tool

Own development:

[https://tradeanalysis.shinyapps.io/trade-data-explorer/](https://tradeanalysis.shinyapps.io/trade-data-explorer/)

## R package for trade data analysis

In order to simplify trade data analysis work, an R package was developed to tackle with some basic operations. 

`tradeAnalysis` package could be found here: [https://github.com/EBukin/tradeAnalysis-pack](https://github.com/EBukin/tradeAnalysis-pack)

Installation in R is the following:

```
install.packages("devtools")
devtools::install_github("EBukin/tradeAnalysis-pack")
library(tradeAnalysis)
```

